# # yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: offcourse

release:
  github:
    owner: geerew
    name: offcourse

builds:
  - id: offcourse
    binary: offcourse
    main: .
    targets:
      # Linux
      - linux_amd64_v1
      - linux_arm64
      - linux_386
      # Mac
      - darwin_amd64_v1
      - darwin_arm64
      # Windows
      - windows_amd64_v1
