name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-ui:
    name: UI Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0
          run_install: true
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 22.19.0
      - name: Lint Check
        working-directory: ./ui
        run: pnpm run lint

  test-backend:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.4
          cache: true
      - name: Install FFmpeg and FFprobe
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          echo "FFmpeg version:"
          ffmpeg -version
          echo "FFprobe version:"
          ffprobe -version
      - name: Verify Dependencies
        run: |
          echo "Checking FFmpeg installation:"
          which ffmpeg
          echo "Checking FFprobe installation:"
          which ffprobe
      - name: Check Go Environment
        run: |
          go version
          go env
      - name: Verify Test Data
        run: |
          ls -la utils/media/probe/testdata/
          file utils/media/probe/testdata/sample.mp4
      - name: Go Test
        run: go test -tags dev -v ./...
