name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  UI-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0
          run_install: false
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.15.0
      - name: build
        working-directory: ./ui
        env:
          PUBLIC_BACKEND_HOST: localhost
          PUBLIC_BACKEND_PORT: 9081
        run: pnpm i && pnpm run build
